### ISSUE TITLE
Connection refused bug

### ISSUE THREAD

**Issue by furkansahin** [CrypDist/CrypDist#10]
We have a connection refused bug and it appears during the communication of the peers while the other peers trying to send the validation messages for the transactions
<img width="801" alt="screen shot 2017-04-24 at 15 11 43" src="https://cloud.githubusercontent.com/assets/6233557/25336430/21a6cf60-2900-11e7-8123-dc09d1ce8d94.png">

**Comment by furkansahin** [comment]
The main problem is obviously resolved but I want to add another problem to this thread.
When we try to connect two clients consequently very quickly (let's say in the same time), they don't see each other.

**Comment by furkansahin** [comment]
@oguzdemir solved that problem, it is stressed for simultaneous accesses by 4 different servers and holded on.

**Comment by oguzdemir** [comment]
Solved with bb3cc32738237dcacb83619c1648d1f8a8c32fc4
